################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/common/FrontendApplication.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/model/Model.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_screen/Screen_1Presenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_screen/Screen_1View.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_lp_statistics_screen/Screen_1_LP_StatisticsPresenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_lp_statistics_screen/Screen_1_LP_StatisticsView.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_statistics_screen/Screen_1_StatisticsPresenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_statistics_screen/Screen_1_StatisticsView.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_screen/Screen_2Presenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_screen/Screen_2View.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm0_screen/Screen_2_PM0Presenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm0_screen/Screen_2_PM0View.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm2_screen/Screen_2_PM2Presenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm2_screen/Screen_2_PM2View.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_3_lt_screen/Screen_3_LTPresenter.cpp \
C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_3_lt_screen/Screen_3_LTView.cpp 

OBJS += \
./Application/User/gui/FrontendApplication.o \
./Application/User/gui/Model.o \
./Application/User/gui/Screen_1Presenter.o \
./Application/User/gui/Screen_1View.o \
./Application/User/gui/Screen_1_LP_StatisticsPresenter.o \
./Application/User/gui/Screen_1_LP_StatisticsView.o \
./Application/User/gui/Screen_1_StatisticsPresenter.o \
./Application/User/gui/Screen_1_StatisticsView.o \
./Application/User/gui/Screen_2Presenter.o \
./Application/User/gui/Screen_2View.o \
./Application/User/gui/Screen_2_PM0Presenter.o \
./Application/User/gui/Screen_2_PM0View.o \
./Application/User/gui/Screen_2_PM2Presenter.o \
./Application/User/gui/Screen_2_PM2View.o \
./Application/User/gui/Screen_3_LTPresenter.o \
./Application/User/gui/Screen_3_LTView.o 

CPP_DEPS += \
./Application/User/gui/FrontendApplication.d \
./Application/User/gui/Model.d \
./Application/User/gui/Screen_1Presenter.d \
./Application/User/gui/Screen_1View.d \
./Application/User/gui/Screen_1_LP_StatisticsPresenter.d \
./Application/User/gui/Screen_1_LP_StatisticsView.d \
./Application/User/gui/Screen_1_StatisticsPresenter.d \
./Application/User/gui/Screen_1_StatisticsView.d \
./Application/User/gui/Screen_2Presenter.d \
./Application/User/gui/Screen_2View.d \
./Application/User/gui/Screen_2_PM0Presenter.d \
./Application/User/gui/Screen_2_PM0View.d \
./Application/User/gui/Screen_2_PM2Presenter.d \
./Application/User/gui/Screen_2_PM2View.d \
./Application/User/gui/Screen_3_LTPresenter.d \
./Application/User/gui/Screen_3_LTView.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/gui/FrontendApplication.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/common/FrontendApplication.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Model.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/model/Model.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1Presenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_screen/Screen_1Presenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1View.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_screen/Screen_1View.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1_LP_StatisticsPresenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_lp_statistics_screen/Screen_1_LP_StatisticsPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1_LP_StatisticsView.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_lp_statistics_screen/Screen_1_LP_StatisticsView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1_StatisticsPresenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_statistics_screen/Screen_1_StatisticsPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_1_StatisticsView.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_1_statistics_screen/Screen_1_StatisticsView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2Presenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_screen/Screen_2Presenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2View.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_screen/Screen_2View.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2_PM0Presenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm0_screen/Screen_2_PM0Presenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2_PM0View.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm0_screen/Screen_2_PM0View.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2_PM2Presenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm2_screen/Screen_2_PM2Presenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_2_PM2View.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_2_pm2_screen/Screen_2_PM2View.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_3_LTPresenter.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_3_lt_screen/Screen_3_LTPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Screen_3_LTView.o: C:/Users/jason/Documents/GenX320_stream/TouchGFX/gui/src/screen_3_lt_screen/Screen_3_LTView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DUSE_BPP=16 -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../TouchGFX/generated/videos/include -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Drivers/product-genx-ctrl/src" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/gui" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Middlewares/FreeRTOS" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/rtos" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/Core" -I"C:/Users/jason/Documents/GenX320_stream/STM32CubeIDE/Application/User/firmware" -I../../USB_DEVICE/App -I../../USB_DEVICE/Target -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-gui

clean-Application-2f-User-2f-gui:
	-$(RM) ./Application/User/gui/FrontendApplication.cyclo ./Application/User/gui/FrontendApplication.d ./Application/User/gui/FrontendApplication.o ./Application/User/gui/FrontendApplication.su ./Application/User/gui/Model.cyclo ./Application/User/gui/Model.d ./Application/User/gui/Model.o ./Application/User/gui/Model.su ./Application/User/gui/Screen_1Presenter.cyclo ./Application/User/gui/Screen_1Presenter.d ./Application/User/gui/Screen_1Presenter.o ./Application/User/gui/Screen_1Presenter.su ./Application/User/gui/Screen_1View.cyclo ./Application/User/gui/Screen_1View.d ./Application/User/gui/Screen_1View.o ./Application/User/gui/Screen_1View.su ./Application/User/gui/Screen_1_LP_StatisticsPresenter.cyclo ./Application/User/gui/Screen_1_LP_StatisticsPresenter.d ./Application/User/gui/Screen_1_LP_StatisticsPresenter.o ./Application/User/gui/Screen_1_LP_StatisticsPresenter.su ./Application/User/gui/Screen_1_LP_StatisticsView.cyclo ./Application/User/gui/Screen_1_LP_StatisticsView.d ./Application/User/gui/Screen_1_LP_StatisticsView.o ./Application/User/gui/Screen_1_LP_StatisticsView.su ./Application/User/gui/Screen_1_StatisticsPresenter.cyclo ./Application/User/gui/Screen_1_StatisticsPresenter.d ./Application/User/gui/Screen_1_StatisticsPresenter.o ./Application/User/gui/Screen_1_StatisticsPresenter.su ./Application/User/gui/Screen_1_StatisticsView.cyclo ./Application/User/gui/Screen_1_StatisticsView.d ./Application/User/gui/Screen_1_StatisticsView.o ./Application/User/gui/Screen_1_StatisticsView.su ./Application/User/gui/Screen_2Presenter.cyclo ./Application/User/gui/Screen_2Presenter.d ./Application/User/gui/Screen_2Presenter.o ./Application/User/gui/Screen_2Presenter.su ./Application/User/gui/Screen_2View.cyclo ./Application/User/gui/Screen_2View.d ./Application/User/gui/Screen_2View.o ./Application/User/gui/Screen_2View.su ./Application/User/gui/Screen_2_PM0Presenter.cyclo ./Application/User/gui/Screen_2_PM0Presenter.d ./Application/User/gui/Screen_2_PM0Presenter.o ./Application/User/gui/Screen_2_PM0Presenter.su ./Application/User/gui/Screen_2_PM0View.cyclo ./Application/User/gui/Screen_2_PM0View.d ./Application/User/gui/Screen_2_PM0View.o ./Application/User/gui/Screen_2_PM0View.su ./Application/User/gui/Screen_2_PM2Presenter.cyclo ./Application/User/gui/Screen_2_PM2Presenter.d ./Application/User/gui/Screen_2_PM2Presenter.o ./Application/User/gui/Screen_2_PM2Presenter.su ./Application/User/gui/Screen_2_PM2View.cyclo ./Application/User/gui/Screen_2_PM2View.d ./Application/User/gui/Screen_2_PM2View.o ./Application/User/gui/Screen_2_PM2View.su ./Application/User/gui/Screen_3_LTPresenter.cyclo ./Application/User/gui/Screen_3_LTPresenter.d ./Application/User/gui/Screen_3_LTPresenter.o ./Application/User/gui/Screen_3_LTPresenter.su ./Application/User/gui/Screen_3_LTView.cyclo ./Application/User/gui/Screen_3_LTView.d ./Application/User/gui/Screen_3_LTView.o ./Application/User/gui/Screen_3_LTView.su

.PHONY: clean-Application-2f-User-2f-gui

